import { spawn, type ChildProcess } from "node:child_process";
import { connect } from "node:net";
import {
  mkdir,
  open,
  readFile,
  readdir,
  rm,
  writeFile,
} from "node:fs/promises";
import { randomBytes } from "node:crypto";
import { homedir } from "node:os";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import type { SystemPermissionKind } from "@polymux/protocol";
import type { Homeserver } from "./server.js";
import { shippedNetworkConfig } from "./shipped-credentials.js";

/**
 * Runs mautrix bridge binaries as supervised children of Polymux, against the
 * embedded homeserver. No Docker, no separate stack: a bridge is a binary in
 * the bridges directory, and everything else — config, registration, tokens,
 * ports, restarts — is owned here.
 *
 * Config strategy: bridgev2 binaries upgrade a partial config in place,
 * filling every missing key with its default, so only the fields that bind
 * the bridge to this homeserver are written. The registration file is
 * generated by the bridge itself (`-g`), which keeps the user namespaces
 * exactly as the bridge expects them rather than as a guess.
 */

export interface BridgeDefinition {
  /** Platform key, e.g. "whatsapp" — used for the provisioning route. */
  name: string;
  binary: string;
  port: number;
  /** Keys written under `network:` in the seed config. */
  network?: Record<string, string>;
  /** Pre-megabridge config layout; see BridgeSpec.legacy. */
  legacy?: boolean;
}

export interface BridgeHostOptions {
  /** Root for per-bridge config/data directories. */
  directory: string;
  /**
   * Where bridge binaries live, named mautrix-<network>, in search order.
   * Normally the copy bundled in the app followed by a writable directory the
   * user can drop extras into — a network upstream ships no macOS build for
   * starts working the moment its binary appears there.
   */
  binariesDirectory: string | string[];
  homeserver: Homeserver;
  /** First provisioning port; each bridge takes the next one up. */
  basePort?: number;
  spawn?: typeof spawn;
  log?: (message: string) => void;
  /** The home directory a bridge's preflight looks in. Overridable for tests. */
  home?: string;
  /** Host operating system. Overridable for cross-platform tests. */
  platform?: NodeJS.Platform;
  /** Host CPU architecture. Overridable for cross-platform tests. */
  arch?: NodeJS.Architecture;
  /**
   * Application credentials shipped with the build, by platform, standing in
   * for ones the user would otherwise register themselves. Overridable so a
   * test can supply a pair without a build that baked one in.
   */
  shippedCredentials?: (platform: string) => Readonly<Record<string, string>>;
  /** Backoff between restarts. Overridable so tests need not wait it out. */
  restartDelaysMs?: readonly number[];
  /**
   * How long `ensure` waits for a started bridge to answer. Zero skips the
   * wait, which is what a test with a fake child wants — nothing it spawns
   * ever binds a port.
   */
  readyTimeoutMs?: number;
}

/** Whether anything is accepting connections on a bridge's provisioning port. */
function accepting(port: number): Promise<boolean> {
  return new Promise((resolve) => {
    const socket = connect({ host: "127.0.0.1", port });
    const settle = (answer: boolean): void => {
      socket.destroy();
      resolve(answer);
    };
    socket.once("connect", () => settle(true));
    socket.once("error", () => settle(false));
    socket.setTimeout(250, () => settle(false));
  });
}

/**
 * One bridge instance: the platform it serves, the binary that serves it, and
 * the network settings that bind the two.
 *
 * Messenger and Instagram share an upstream repository and configuration
 * shape, but are separate executables. Instagram's old `mautrix-meta` mode was
 * retired after v26.07; keeping it on that compatibility build leaves a login
 * authenticated but unable to maintain Meta's realtime connection.
 */
export interface BridgeSpec {
  /** Platform key, matching the protocol catalogue and the provisioning route. */
  platform: string;
  /** Executable name inside the binaries directory. */
  binary: string;
  /** Operating systems upstream can actually run on. A user-supplied native
   * binary still overrides this, but the packaged app must not advertise a
   * bridge that cannot be built for the current host. */
  platforms?: readonly NodeJS.Platform[];
  /** Exact packaged targets when support differs by architecture. */
  targets?: readonly string[];
  /** Keys written under `network:` in the seed config. */
  network?: Record<string, string>;
  /**
   * Pre-megabridge config layout: database under `appservice:`, provisioning
   * under `bridge:`, no `network:` block. The binary rejects the modern shape
   * outright, so the seed has to match its generation.
   */
  legacy?: boolean;
  /**
   * `network:` keys the binary refuses to start without, each mapped to the
   * placeholder upstream writes for it (empty string when it writes none).
   * Nothing here can be guessed or defaulted — it is the user's own credential.
   *
   * The placeholder is the whole point: a bridgev2 binary fills in every
   * missing key when it upgrades the config in place, so after one run these
   * keys are *present* and still worthless. Presence alone would read a
   * config the user has never touched as fully configured.
   */
  requires?: Readonly<Record<string, string>>;
  /**
   * A precondition on this Mac rather than in the config: a file the bridge
   * must be able to read, a service that must be present. Returns what is
   * holding the bridge back, or null when nothing is.
   */
  preflight?: (context: { home: string }) => Promise<BridgeBlock | null>;
}

/** Why a bridge is not running, and whether a button could fix it. */
export interface BridgeBlock {
  /** What the user is told. */
  reason: string;
  /**
   * The macOS grant that would unblock it, when one would. Carried separately
   * from the prose so the UI can offer the grant rather than describe it — a
   * blocker with no permission here is one no button can resolve.
   */
  permission?: SystemPermissionKind;
  /**
   * Whether looking again could clear this. A precondition can be satisfied
   * while Polymux is running, so it is worth re-checking; a bridge that burned
   * its restart budget is not, and retrying it on a timer would just rebuild
   * the crash loop the budget existed to stop.
   */
  retryable: boolean;
}

/**
 * iMessage is read out of this Mac's own Messages database, which macOS hands
 * to no one without Full Disk Access. Without the grant the bridge dies on its
 * first query every time it starts, so the grant is checked here and the
 * bridge waits, with something the user can act on, instead.
 */
export async function messagesDatabaseAccess({
  home,
  childProbe = childCanRead,
}: {
  home: string;
  childProbe?: (database: string) => Promise<boolean>;
}): Promise<BridgeBlock | null> {
  if (process.platform !== "darwin") return null;
  const database = path.join(home, "Library", "Messages", "chat.db");
  // Opening it is the check: TCC denies the read itself, so anything short of
  // actually opening the file reports access this process does not have.
  const handle = await open(database, "r").catch(
    (error: NodeJS.ErrnoException) => error,
  );
  if (!(handle instanceof Error)) {
    await handle.close().catch((): undefined => undefined);
    // The bridge is a separate executable. TCC normally attributes a child to
    // the app that launched it, but proving only the Electron main process can
    // read this file would turn a stale or mismatched grant into a crash loop.
    // Exercise the same parent -> child boundary before allowing the bridge to
    // start. `head` reads at most one byte and never copies message contents
    // back into Polymux.
    if (await childProbe(database)) return null;
    return {
      reason:
        "Polymux has Full Disk Access, but child processes launched by it cannot read your Messages database. Restart Polymux after granting access.",
      permission: "full-disk-access",
      retryable: true,
    };
  }
  // No grant creates a database that was never made, so this one is deliberately
  // offered without a permission: a button here would promise a fix it has not got.
  if (handle.code === "ENOENT")
    return {
      reason:
        "Messages has never been set up on this Mac, so there is no conversation database to bridge.",
      retryable: true,
    };
  return {
    reason: "Polymux needs Full Disk Access to read your Messages database.",
    permission: "full-disk-access",
    retryable: true,
  };
}

function childCanRead(database: string): Promise<boolean> {
  return new Promise((resolve) => {
    const child = spawn("/usr/bin/head", ["-c", "1", database], {
      stdio: "ignore",
    });
    let settled = false;
    const finish = (readable: boolean): void => {
      if (settled) return;
      settled = true;
      resolve(readable);
    };
    child.once("error", () => finish(false));
    child.once("exit", (code) => finish(code === 0));
  });
}

/**
 * Every network this host knows how to run, whether or not its binary is
 * installed. Discovery filters this against what is on disk; the catalogue
 * itself is what "supported" means, so the UI can name what is missing rather
 * than pretending it does not exist.
 */
export const BRIDGE_FLEET: readonly BridgeSpec[] = [
  { platform: "whatsapp", binary: "mautrix-whatsapp" },
  // Telegram will not talk to an application it does not know about, so this
  // binary needs a pair before it can start: the one the build ships, or the
  // user's own. The values below are the example pair the binary itself writes
  // into a fresh config and then refuses to start on, which is why they have
  // to count as unset.
  {
    platform: "telegram",
    binary: "mautrix-telegram",
    requires: { api_id: "12345", api_hash: "tjyd5yge35lbodk1xwzw2jstp90k55qz" },
  },
  {
    platform: "signal",
    binary: "mautrix-signal",
    platforms: ["darwin", "linux"],
  },
  {
    platform: "discord",
    binary: "mautrix-discord",
    legacy: true,
    platforms: ["darwin", "linux"],
  },
  { platform: "slack", binary: "mautrix-slack" },
  // These use the same config shape but separate executables upstream.
  {
    platform: "messenger",
    binary: "mautrix-meta",
    network: { mode: "messenger" },
  },
  {
    platform: "instagram",
    binary: "mautrix-instagram",
    // Rich-media backfill is the difference between a historical reel and
    // only its cover image. Live and backfilled reels should both attempt the
    // real video; an expired source URL can still fall back to its post link.
    network: {
      mode: "instagram",
      disable_xma_backfill: "false",
      disable_xma_always: "false",
    },
  },
  {
    platform: "googlechat",
    binary: "mautrix-googlechat",
    targets: ["darwin-arm64", "linux-x64", "win32-x64"],
  },
  { platform: "gmessages", binary: "mautrix-gmessages" },
  { platform: "linkedin", binary: "mautrix-linkedin" },
  { platform: "twitter", binary: "mautrix-twitter" },
  { platform: "bluesky", binary: "mautrix-bluesky" },
  { platform: "gvoice", binary: "mautrix-gvoice" },
  // Self-hosted and cloud Zulip both work: the organisation's own URL is part
  // of the login rather than the config, so nothing here has to name a server.
  { platform: "zulip", binary: "mautrix-zulip" },
  // Reads the Messages database on this Mac rather than a remote network.
  {
    platform: "imessage",
    binary: "mautrix-imessage",
    platforms: ["darwin"],
    preflight: messagesDatabaseAccess,
  },
];

/**
 * How a bridge records that an account is linked to it, newest generation
 * first. Read straight out of the bridge's own database so the answer survives
 * a Polymux that has never seen the login happen — the alternative, Polymux
 * keeping its own list, is a second source of truth that starts out empty and
 * would silently stop delivering messages for anyone upgrading.
 */
const LINKED_ACCOUNT_QUERIES = [
  "select count(*) as linked from user_login",
  // Pre-megabridge bridges hang the account off the user row itself.
  `select count(*) as linked from "user" where discord_token is not null and discord_token != ''`,
];

const RESTART_DELAYS_MS = [1_000, 5_000, 15_000, 60_000];
/**
 * How many times in a row a bridge may die before it is left down. A binary
 * that has failed this many times is failing for a reason another restart will
 * not change — a revoked grant, a database it cannot open — and a permanent
 * once-a-minute loop only buries the line that explains why.
 */
const RESTART_LIMIT = 5;
/**
 * How long `ensure` waits for a bridge it just started to accept connections.
 * Measured cold starts answer in well under a tenth of a second, so this is a
 * ceiling for something having gone wrong rather than a delay anyone waits out.
 */
const READY_TIMEOUT_MS = 5_000;
/**
 * A child that stayed up this long counts as having started successfully, so a
 * bridge that runs all day and then crashes gets the full restart budget again
 * rather than inheriting a count from the morning.
 */
const HEALTHY_UPTIME_MS = 60_000;

/**
 * Lines emitted at warning/error level for connection churn the bridge itself
 * handles. They are not actionable and do not mean the bridge process or its
 * linked account is down. Keeping them out here also prevents one of these
 * routine EOFs becoming the "reason" shown if the process later fails for an
 * unrelated cause.
 *
 * The bridges are seeded with mautrix's `pretty-colored` writer, which wraps
 * timestamps, levels, and every `key=` in ANSI colour sequences — so the raw
 * stream never contains the plain `key=value` text these patterns look for,
 * and the escapes would otherwise be quoted verbatim into stored failure
 * reasons. Lines are stripped once, and the stripped form is what gets
 * matched, logged, and quoted.
 */
const ANSI_COLOURS = /\x1b\[[0-9;]*m/g;

function routineBridgeOutput(platform: string, line: string): boolean {
  // Both WhatsApp and Messenger use whatsmeow's websocket transport. These
  // failures are the reconnect trigger itself, not a terminal bridge error.
  if (line.includes("component=whatsmeow"))
    return (
      line.includes("Received stream end frame") ||
      line.includes(
        "Got 503 stream error, assuming automatic reconnect will handle it",
      ) ||
      line.includes("Keepalive timed out") ||
      line.includes(
        "Error reading from websocket: failed to get reader: failed to read frame header: EOF",
      ) ||
      (line.includes(
        "Error reading from websocket: failed to get reader: failed to read frame header:",
      ) &&
        (line.includes("read: connection reset by peer") ||
          line.includes("read: can't assign requested address")))
    );

  // A receipt older than the locally bridged history has no Matrix event it
  // can point at. bridgev2 returns Ignored here; it is not a failed receipt.
  if (
    line.includes("No target message found for read receipt") &&
    line.includes("bridge_evt_type=RemoteEventReadReceipt")
  )
    return true;

  if (platform === "instagram")
    return (
      (line.includes("Ignoring event with no portal") &&
        (line.includes("typename=SlideUQPPCreate1To1Thread") ||
          line.includes("typename=SlideUQPPUserReachabilityStatus"))) ||
      (line.includes("Failed to reupload room avatar") &&
        line.includes('error="no Get function provided for avatar"') &&
        line.includes('action="create matrix room"') &&
        line.includes("bridge_evt_type=RemoteEventChatResync"))
    );

  if (platform === "telegram")
    return (
      line.includes("ignoring unknown action type") &&
      line.includes("action_type=*tg.MessageActionChatJoinedByRequest")
    );

  if (platform === "messenger") {
    if (line.includes("component=messagix"))
      return (
        line.includes(
          'Error reading message from socket error="failed to get reader: failed to read frame header: EOF"',
        ) ||
        line.includes(
          'Error in connection, reconnecting error="error in read loop: failed to read message: failed to get reader: failed to read frame header: EOF"',
        ) ||
        line.includes("No transactions found")
      );

    // Meta's Lightspeed schema includes optional, server-controlled data that
    // the bridge deliberately skips when it cannot decode or use it. These
    // exact fields are logging/admin-button metadata, not message content.
    if (line.includes("global_log=true"))
      return (
        (line.includes("Failed to set int64") &&
          line.includes("field_name=AttachmentLoggingType") &&
          line.includes("struct_name=LSInsertXmaAttachment") &&
          line.includes("val_type=string")) ||
        (line.includes("Skipping dependency with no reference") &&
          (line.includes("reference_name=applyAdminMessageCTAV2") ||
            line.includes("reference_name=setRegionHint"))) ||
        (line.includes("Unknown dependency in sp") &&
          line.includes("dependency=setRegionHint"))
      );
  }
  return false;
}

export class BridgeHost {
  readonly #options: BridgeHostOptions;
  readonly #children = new Map<string, ChildProcess>();
  readonly #restartCounts = new Map<string, number>();
  /** Why a bridge is not running, for platforms that are installed but down. */
  readonly #blocked = new Map<string, BridgeBlock>();
  /** The last line each bridge printed, so a failure can quote its own reason. */
  readonly #lastOutput = new Map<string, string>();
  /** Starts in flight, so hover-then-click cannot spawn a bridge twice. */
  readonly #starting = new Map<string, Promise<void>>();
  #closed = false;
  /** Pending restart backoffs, cancelled on close so shutdown is not held up. */
  readonly #restartTimers = new Set<NodeJS.Timeout>();

  constructor(options: BridgeHostOptions) {
    this.#options = options;
  }

  /**
   * Ports are assigned from the catalogue's own order, not from what happens
   * to be installed, so a platform keeps the same port when its neighbours are
   * added or removed — a port that moved under a running bridge would strand
   * its registration.
   */
  #port(platform: string): number {
    const base = this.#options.basePort ?? 29_800;
    return base + BRIDGE_FLEET.findIndex((spec) => spec.platform === platform);
  }

  /** Where each installed binary was found, first directory winning. */
  async #locate(): Promise<Map<string, string>> {
    const directories = Array.isArray(this.#options.binariesDirectory)
      ? this.#options.binariesDirectory
      : [this.#options.binariesDirectory];
    const found = new Map<string, string>();
    for (const directory of directories) {
      const entries = await readdir(directory).catch((): string[] => []);
      for (const entry of entries) {
        const installed = path.join(directory, entry);
        if (!found.has(entry)) found.set(entry, installed);
        // Windows executables need their native suffix, while the bridge
        // catalogue deliberately stays platform-neutral. Index the native
        // filename under the catalogue name too so discovery, inventory and
        // port assignment remain identical on every OS.
        if (entry.toLowerCase().endsWith(".exe")) {
          const portableName = entry.slice(0, -4);
          if (!found.has(portableName)) found.set(portableName, installed);
        }
      }
    }
    return found;
  }

  /** Bridge binaries present on disk, with their assigned ports. */
  async discover(): Promise<BridgeDefinition[]> {
    const found = await this.#locate();
    return BRIDGE_FLEET.filter((spec) => found.has(spec.binary)).map(
      (spec) => ({
        name: spec.platform,
        binary: found.get(spec.binary)!,
        port: this.#port(spec.platform),
        // A shipped pair joins the keys the spec pins, so it is seeded into the
        // config like any other `network:` value and the bridge starts on it.
        // Anything the user recorded still wins: every writer here merges the
        // config's own values over these.
        network: this.#withShipped(spec.platform, spec.network),
        legacy: spec.legacy,
      }),
    );
  }

  /** What Polymux supplies for a platform in place of the user's own pair. */
  #shipped(platform: string): Readonly<Record<string, string>> {
    return (this.#options.shippedCredentials ?? shippedNetworkConfig)(platform);
  }

  #withShipped(
    platform: string,
    network: Record<string, string> | undefined,
  ): Record<string, string> | undefined {
    const shipped = this.#shipped(platform);
    if (Object.keys(shipped).length === 0) return network;
    return { ...network, ...shipped };
  }

  /**
   * Which platforms could run here, which are waiting on their binary, and
   * which are installed but held back. The comms layer reports this so a
   * platform that was never installed reads as "not installed", one waiting on
   * a credential says so, and only a genuine silence reads as a bridge that
   * failed to answer.
   */
  async inventory(): Promise<
    {
      platform: string;
      binary: string;
      supported: boolean;
      installed: boolean;
      blocked: BridgeBlock | null;
      running: boolean;
    }[]
  > {
    const found = await this.#locate();
    const hostPlatform = this.#options.platform ?? process.platform;
    const hostArch = this.#options.arch ?? process.arch;
    const hostTarget = `${hostPlatform}-${hostArch}`;
    return BRIDGE_FLEET.map((spec) => {
      const installed = found.has(spec.binary);
      return {
        platform: spec.platform,
        binary: spec.binary,
        supported:
          installed ||
          ((!spec.platforms || spec.platforms.includes(hostPlatform)) &&
            (!spec.targets || spec.targets.includes(hostTarget))),
        installed,
        blocked: this.#blocked.get(spec.platform) ?? null,
        // Installed but not running is a bridge waiting to be asked for, which
        // has to read differently from one that was asked for and did not answer.
        // One still coming up counts as the former: it has a child process but no
        // open port yet, and probing it in that window is how a bridge starting
        // normally got reported as broken.
        running:
          this.#children.has(spec.platform) && !this.#starting.has(spec.platform),
      };
    });
  }

  async startAll(): Promise<BridgeDefinition[]> {
    const bridges = await this.discover();
    for (const bridge of bridges) await this.#start(bridge);
    return bridges;
  }

  /**
   * Whether an account is linked to this bridge, answered from its database
   * without starting it. A bridge with an account is receiving messages and
   * has to be running; one without is only ever wanted from the moment someone
   * opens it, which on most machines is most of the fleet.
   */
  hasLinkedAccount(platform: string): boolean {
    let database: DatabaseSync;
    try {
      // A bridge that has never run has no database, and so no account.
      database = new DatabaseSync(
        path.join(this.#options.directory, platform, "bridge.db"),
        {
          readOnly: true,
        },
      );
    } catch {
      return false;
    }
    try {
      for (const query of LINKED_ACCOUNT_QUERIES) {
        try {
          const row = database.prepare(query).get() as
            { linked: number } | undefined;
          if (row) return Number(row.linked) > 0;
        } catch {
          // Not this generation's schema; try the next one.
        }
      }
      return false;
    } finally {
      database.close();
    }
  }

  /**
   * What has to be up for Polymux to do its job: the bridges carrying an
   * account. The rest of the installed fleet stays down until `ensure` is
   * asked for it — a dozen idle Go processes and their databases is a real
   * cost to pay for networks nobody has signed into.
   */
  async startLinked(): Promise<BridgeDefinition[]> {
    const bridges = (await this.discover()).filter((bridge) =>
      this.hasLinkedAccount(bridge.name),
    );
    for (const bridge of bridges) await this.#start(bridge);
    return bridges;
  }

  /**
   * Brings one bridge up, resolving once it is running (or once it is known
   * not to be startable). Idempotent and safe to call repeatedly: the UI fires
   * it on hover as well as on click, so the common case is a bridge that is
   * already up or already coming up, and neither may spawn a second copy.
   */
  async ensure(platform: string): Promise<void> {
    if (this.#children.has(platform)) return;
    const inFlight = this.#starting.get(platform);
    if (inFlight) return inFlight;

    const attempt = (async () => {
      const bridge = (await this.discover()).find(
        (entry) => entry.name === platform,
      );
      if (!bridge) return;
      await this.#start(bridge);
      await this.#waitUntilAnswering(bridge);
    })();
    this.#starting.set(platform, attempt);
    try {
      await attempt;
    } finally {
      this.#starting.delete(platform);
    }
  }

  /**
   * The `network:` values recorded for a platform, read back out of the config
   * the bridge actually runs on. Only keys the caller asks about are returned,
   * and a value still equal to the seed placeholder counts as unset.
   */
  async networkConfig(platform: string): Promise<Record<string, string>> {
    const configPath = path.join(
      this.#options.directory,
      platform,
      "config.yaml",
    );
    const source = await readFile(configPath, "utf8").catch((): string => "");
    const block = source.match(/^network:\n((?:[ \t]+.*\n?)*)/m)?.[1];
    if (!block) return {};
    // Upstream's own example values are as unset as an empty string: the binary
    // writes them itself and then refuses to start on them, so reading them
    // back as answers is how a bridge nobody configured looks configured.
    const placeholders =
      BRIDGE_FLEET.find((entry) => entry.platform === platform)?.requires ?? {};
    const values: Record<string, string> = {};
    for (const line of block.split("\n")) {
      const match = line.match(/^\s+([A-Za-z0-9_]+):\s*(.*?)\s*$/);
      if (!match) continue;
      const [, key, value] = match;
      if (value === "" || value === '""' || value === placeholders[key])
        continue;
      values[key] = value;
    }
    return values;
  }

  /**
   * Writes values into a bridge's `network:` block and restarts it. The config
   * may not exist yet — a bridge whose credentials are supplied before its
   * first run is seeded here — and a running child is stopped first so the
   * replacement reads the new file rather than racing it.
   */
  async configureNetwork(
    platform: string,
    values: Record<string, string>,
  ): Promise<void> {
    const spec = BRIDGE_FLEET.find((entry) => entry.platform === platform);
    if (!spec) throw new Error(`${platform} is not a bridge this host runs.`);

    const directory = path.join(this.#options.directory, platform);
    await mkdir(directory, { recursive: true });
    const configPath = path.join(directory, "config.yaml");
    const existing = await readFile(configPath, "utf8").catch(
      (): string | null => null,
    );
    // The user's own values last: supplying a pair is how you override the one
    // Polymux ships, and a partial answer must not strip the rest of the block.
    const merged = { ...spec.network, ...this.#shipped(platform), ...values };
    const bridge: BridgeDefinition = {
      name: platform,
      binary: "",
      port: this.#port(platform),
      network: merged,
    };
    await writeFile(
      configPath,
      existing === null
        ? this.#seedConfig(bridge)
        : withNetwork(existing, merged),
      "utf8",
    );

    // Restart only this one. `#supervise`'s exit handler brings it back with
    // the config just written, so nothing else needs to know.
    this.#restartCounts.set(platform, 0);
    const child = this.#children.get(platform);
    if (child) {
      child.kill("SIGTERM");
      return;
    }

    // Nothing is running: the bridge was parked waiting for exactly these
    // values, or it exhausted its restarts, and in either case no exit handler
    // is going to bring it back. Start it here. A failure is logged rather
    // than thrown — the configuration is saved either way, and reporting the
    // save as failed would send the user back to retype it.
    this.#blocked.delete(platform);
    const definition = (await this.discover()).find(
      (entry) => entry.name === platform,
    );
    if (!definition) return;
    await this.#start(definition).catch((error: unknown) => {
      this.#options.log?.(
        `[${platform}] failed to start after configuration: ${
          error instanceof Error ? error.message : String(error)
        }`,
      );
    });
  }

  /**
   * Re-checks the bridges that were held back by something the user could have
   * satisfied since — a grant given in System Settings, a Messages database
   * that now exists — and starts whichever are clear. Cheap when nothing has
   * changed, since a precondition is a file probe, so it is safe to call every
   * time the window comes back.
   *
   * Deliberately skips a bridge that burned its restart budget: that one is
   * not waiting on the user, and retrying it here would rebuild the very loop
   * the budget exists to stop.
   */
  async retryBlocked(): Promise<void> {
    const waiting = new Set(
      [...this.#blocked]
        .filter(
          ([platform, block]) =>
            block.retryable && !this.#children.has(platform),
        )
        .map(([platform]) => platform),
    );
    if (waiting.size === 0) return;
    for (const bridge of await this.discover()) {
      if (!waiting.has(bridge.name)) continue;
      await this.#start(bridge).catch((error: unknown) => {
        this.#options.log?.(
          `[${bridge.name}] retry failed: ${error instanceof Error ? error.message : String(error)}`,
        );
      });
    }
  }

  /**
   * Waits for a bridge that has just been spawned to accept connections.
   *
   * `#start` returns as soon as the child exists, which is some tens of
   * milliseconds before its provisioning API is listening — and the caller
   * reads the fleet the moment `ensure` resolves. Returning early meant
   * probing a bridge that was coming up perfectly well and reporting it as not
   * responding, which then stuck on screen because nothing re-read it.
   *
   * Gives up once the child is gone: a bridge that died is not going to answer,
   * and supervision has already recorded why.
   */
  async #waitUntilAnswering(bridge: BridgeDefinition): Promise<void> {
    const budget = this.#options.readyTimeoutMs ?? READY_TIMEOUT_MS;
    if (budget <= 0) return;
    const deadline = Date.now() + budget;
    while (Date.now() < deadline && this.#children.has(bridge.name)) {
      if (await accepting(bridge.port)) return;
      await new Promise((resolve) => setTimeout(resolve, 15));
    }
  }

  async close(): Promise<void> {
    this.#closed = true;
    for (const timer of this.#restartTimers) clearTimeout(timer);
    this.#restartTimers.clear();
    for (const child of this.#children.values()) child.kill("SIGTERM");
    this.#children.clear();
  }

  async #start(bridge: BridgeDefinition): Promise<void> {
    const directory = path.join(this.#options.directory, bridge.name);
    await mkdir(directory, { recursive: true });
    const configPath = path.join(directory, "config.yaml");
    const registrationPath = path.join(directory, "registration.yaml");

    const existing = await readFile(configPath, "utf8").catch(
      (): string | null => null,
    );
    if (existing === null) {
      await writeFile(configPath, this.#seedConfig(bridge), "utf8");
    } else if (bridge.legacy && /^database:/m.test(existing)) {
      // An earlier Polymux seeded this legacy bridge with the modern layout,
      // which its generation rejects at startup — it has been crash-looping
      // ever since. Reseed in the shape it accepts. The registration goes with
      // it: the reseed mints new tokens, and a registration carrying the old
      // ones would leave the two halves unable to authenticate.
      //
      // The marker is a *top-level* `database:`, which only the modern seed
      // writes — a legacy bridge keeps it under `appservice:`. An earlier
      // version looked for `software:` instead, which these binaries also
      // accept and write back when they upgrade the config in place: that
      // matched a config this branch had just written, so every launch threw
      // away working tokens and minted a new registration, forever.
      this.#options.log?.(
        `[${bridge.name}] config was seeded in a layout this bridge rejects; reseeding`,
      );
      await writeFile(configPath, this.#seedConfig(bridge), "utf8");
      await rm(registrationPath, { force: true });
    } else if (bridge.network) {
      // A shared binary that predates its `network:` block (or gained new
      // required keys) exits at startup. Merge in what the spec requires,
      // keeping every value already recorded — the user's own entries win.
      const recorded = await this.networkConfig(bridge.name);
      const missing = Object.entries(bridge.network).filter(
        ([key]) => !(key in recorded),
      );
      if (missing.length > 0) {
        this.#options.log?.(
          `[${bridge.name}] config was missing ${missing.map(([key]) => key).join(", ")}; repaired`,
        );
        await writeFile(
          configPath,
          withNetwork(existing, {
            ...Object.fromEntries(missing),
            ...recorded,
          }),
          "utf8",
        );
      }
    }

    // Checked once the config is on disk — a `requires` key is read back out
    // of it — but before anything is spawned. A bridge that cannot succeed is
    // never launched, so it never crash-loops and never registers an
    // appservice the homeserver would then route to nothing.
    const blocked = await this.#blockReason(bridge);
    if (blocked) {
      this.#blocked.set(bridge.name, blocked);
      this.#options.log?.(`[${bridge.name}] not started: ${blocked.reason}`);
      return;
    }
    this.#blocked.delete(bridge.name);

    const hasRegistration = await readFile(registrationPath, "utf8").then(
      () => true,
      () => false,
    );
    if (!hasRegistration) {
      // The bridge writes its own registration, deriving the ghost namespaces
      // from its username template so they are never out of sync.
      await this.#run(
        bridge.binary,
        ["-c", configPath, "-r", registrationPath, "-g"],
        directory,
      );
    }

    const registration = parseRegistration(
      await readFile(registrationPath, "utf8"),
    );
    await this.#reconcileWindowsConfig(
      directory,
      configPath,
      registration,
    );

    /**
     * Last, because a binary writes its own defaults over the whole config
     * whenever it reads one — including the `-g` pass just above, on a config
     * this launch seeded seconds ago. Repairing before that would be repairing
     * the file the bridge is about to overwrite.
     *
     * What it defaults to: backfill off, no history queue, history limits an
     * order of magnitude below what a chat shows on the phone, no double
     * puppet secret, and WhatsApp asked for only the recent slice of its
     * history. Each one is a conversation that opens empty or reads as if the
     * other person sent everything in it.
     */
    const onDisk = await readFile(configPath, "utf8").catch(
      (): string | null => null,
    );
    if (onDisk !== null) {
      const repaired = repairConfig(onDisk, {
        serverName: this.#options.homeserver.serverName,
        baseUrl: this.#options.homeserver.baseUrl,
        legacy: bridge.legacy,
        platform: bridge.name,
      });
      if (repaired !== onDisk) {
        this.#options.log?.(
          `[${bridge.name}] config was missing history, logout cleanup or double puppeting; repaired`,
        );
        await writeFile(configPath, repaired, "utf8");
      }
    }

    // A crashed or force-quit Polymux leaves its bridge children orphaned, and a
    // second copy would fight the first for the appservice port. Reap the
    // previous incumbent before spawning a new one.
    await reapStalePid(path.join(directory, "bridge.pid"));

    this.#options.homeserver.registerAppservice({
      id: registration.id ?? bridge.name,
      asToken: registration.asToken,
      hsToken: registration.hsToken,
      url: registration.url ?? `http://127.0.0.1:${bridge.port}`,
      // Deliberately NOT the registration's sender_localpart: mautrix writes a
      // random string there and then acts as its configured bot username, so
      // the bot binding has to follow the config this host generated.
      senderLocalpart: `${bridge.name}bot`,
      receiveEphemeral: registration.receiveEphemeral,
      userNamespaces: registration.userNamespaces,
    });
    this.#options.homeserver.setProvisioningTarget(
      bridge.name,
      `http://127.0.0.1:${bridge.port}`,
    );
    this.#supervise(bridge, configPath, directory);
  }

  /**
   * mautrix writes config updates through an atomic temporary file. Windows
   * cannot rename that file over an existing destination, so the completed
   * config is left beside `config.yaml` as `mautrix-config-<number>.yaml`.
   * During registration generation this is fatal: the registration receives
   * fresh tokens while the config keeps the previous pair, and the bridge is
   * then rejected by the homeserver.
   *
   * Adopt the completed config whose tokens match the registration before the
   * bridge starts. If an older install has already lost that temporary file,
   * aligning the two token fields still repairs it without requiring the user
   * to reinstall anything.
   */
  async #reconcileWindowsConfig(
    directory: string,
    configPath: string,
    registration: ParsedRegistration,
  ): Promise<void> {
    if ((this.#options.platform ?? process.platform) !== "win32") return;
    const names = await readdir(directory).catch((): string[] => []);
    const temporary = names.filter((name) =>
      /^mautrix-config-\d+\.yaml$/.test(name),
    );
    let source = await readFile(configPath, "utf8");
    for (const name of temporary) {
      const candidate = await readFile(path.join(directory, name), "utf8").catch(
        (): string => "",
      );
      if (
        nestedScalar(candidate, "as_token") === registration.asToken &&
        nestedScalar(candidate, "hs_token") === registration.hsToken
      ) {
        source = candidate;
        this.#options.log?.(
          `[${path.basename(directory)}] completed the config update left pending by Windows`,
        );
        break;
      }
    }
    const reconciled = withRegistrationTokens(source, registration);
    if (reconciled !== (await readFile(configPath, "utf8")))
      await writeFile(configPath, reconciled, "utf8");
    await Promise.all(
      temporary.map((name) =>
        rm(path.join(directory, name), { force: true }).catch(
          (): undefined => undefined,
        ),
      ),
    );
  }

  /**
   * Why this bridge cannot run yet, or null when nothing is holding it back.
   * Both kinds of answer are the user's to give — a credential Polymux will not
   * invent, a grant only macOS can hand over — so neither is something a
   * restart can resolve.
   */
  async #blockReason(bridge: BridgeDefinition): Promise<BridgeBlock | null> {
    const spec = BRIDGE_FLEET.find((entry) => entry.platform === bridge.name);
    if (!spec) return null;
    if (spec.requires) {
      // A shipped pair answers the requirement before the config that will
      // carry it has been written: the block is checked on the way to the
      // first start, and the seed happens during it. Without this the bridge
      // would be held back waiting for a credential it already has.
      const recorded = {
        ...(await this.networkConfig(bridge.name)),
        ...this.#shipped(bridge.name),
      };
      const missing = Object.keys(spec.requires).filter(
        (key) => !recorded[key],
      );
      if (missing.length > 0)
        return {
          reason: `This bridge needs ${missing.join(" and ")} of your own before it can connect, so it has not been started.`,
          retryable: true,
        };
    }
    return (
      (await spec.preflight?.({ home: this.#options.home ?? homedir() })) ??
      null
    );
  }

  #supervise(
    bridge: BridgeDefinition,
    configPath: string,
    directory: string,
  ): void {
    if (this.#closed) return;
    // Both streams: the seed config points mautrix's logger at stdout, so a
    // bridge that dies on startup explains itself there — an exit code alone
    // (the only thing visible before this) says nothing anyone can act on.
    const child = (this.#options.spawn ?? spawn)(
      bridge.binary,
      ["-c", configPath],
      {
        cwd: directory,
        stdio: ["ignore", "pipe", "pipe"],
        windowsHide: true,
      },
    );
    const startedAt = Date.now();
    this.#children.set(bridge.name, child);
    if (child.pid !== undefined)
      void writeFile(
        path.join(directory, "bridge.pid"),
        String(child.pid),
        "utf8",
      ).catch((): undefined => undefined);
    const emit = (line: string): void => {
      const text = line.replace(ANSI_COLOURS, "").trimEnd();
      if (!text || routineBridgeOutput(bridge.name, text)) return;
      this.#lastOutput.set(bridge.name, text);
      this.#options.log?.(`[${bridge.name}] ${text}`);
    };
    const relay = (stream: ChildProcess["stdout"]): void => {
      if (!stream) return;
      let pending = "";
      stream.on("data", (chunk: Buffer | string) => {
        const lines = (pending + chunk.toString()).split(/\r?\n/);
        pending = lines.pop() ?? "";
        for (const line of lines) emit(line);
      });
      stream.on("end", () => {
        if (pending) emit(pending);
        pending = "";
      });
    };
    relay(child.stdout);
    relay(child.stderr);
    child.on("exit", (code) => {
      this.#children.delete(bridge.name);
      if (this.#closed) return;
      // A bridge that was up long enough to be working starts its budget over,
      // so one crash after a long run is not charged against the failures that
      // happened at launch.
      const healthy = Date.now() - startedAt >= HEALTHY_UPTIME_MS;
      const attempt = healthy ? 0 : (this.#restartCounts.get(bridge.name) ?? 0);
      this.#restartCounts.set(bridge.name, attempt + 1);

      if (attempt + 1 >= RESTART_LIMIT) {
        const reason = this.#lastOutput.get(bridge.name);
        this.#blocked.set(bridge.name, {
          reason: `${bridge.name} keeps failing to start and has been left down${reason ? `: ${reason}` : "."}`,
          retryable: false,
        });
        this.#options.log?.(
          `[${bridge.name}] exited with code ${code ?? "signal"} ${attempt + 1} times; leaving it down`,
        );
        return;
      }

      const delays = this.#options.restartDelaysMs ?? RESTART_DELAYS_MS;
      const delay = delays[Math.min(attempt, delays.length - 1)];
      this.#options.log?.(
        `[${bridge.name}] exited with code ${code ?? "signal"}; restarting in ${delay / 1000}s`,
      );
      const timer = setTimeout(() => {
        this.#restartTimers.delete(timer);
        void this.#supervise(bridge, configPath, directory);
      }, delay);
      this.#restartTimers.add(timer);
    });
  }

  #run(binary: string, args: string[], cwd: string): Promise<void> {
    return new Promise((resolve, reject) => {
      const child = (this.#options.spawn ?? spawn)(binary, args, {
        cwd,
        stdio: ["ignore", "ignore", "pipe"],
        windowsHide: true,
      });
      let stderr = "";
      child.stderr?.on(
        "data",
        (chunk: Buffer) => (stderr += chunk.toString("utf8")),
      );
      child.on("error", reject);
      child.on("exit", (code) => {
        if (code === 0) resolve();
        else
          reject(
            new Error(
              `${path.basename(binary)} ${args.join(" ")} failed: ${stderr.trim()}`,
            ),
          );
      });
    });
  }

  /**
   * The minimal config a bridgev2 binary needs to bind to the embedded
   * homeserver; the binary upgrades it in place, appending every other key
   * with its default. Tokens are generated here so the registration and the
   * config can never disagree.
   */
  #seedConfig(bridge: BridgeDefinition): string {
    const homeserver = this.#options.homeserver;
    const asToken = randomBytes(32).toString("hex");
    const hsToken = randomBytes(32).toString("hex");
    const provisioningSecret = randomBytes(32).toString("hex");
    // A pre-megabridge binary rejects the modern layout at startup ("
    // appservice.database not configured"), so it gets its own generation's
    // shape: database inside `appservice:`, provisioning inside `bridge:`.
    if (bridge.legacy)
      return [
        "homeserver:",
        `    address: ${homeserver.baseUrl}`,
        `    domain: ${homeserver.serverName}`,
        "appservice:",
        `    id: ${bridge.name}`,
        `    address: http://127.0.0.1:${bridge.port}`,
        "    hostname: 127.0.0.1",
        `    port: ${bridge.port}`,
        `    as_token: ${asToken}`,
        `    hs_token: ${hsToken}`,
        "    bot:",
        `        username: ${bridge.name}bot`,
        "    database:",
        "        type: sqlite3-fk-wal",
        "        uri: file:bridge.db?_txlock=immediate",
        "bridge:",
        "    provisioning:",
        "        prefix: /_matrix/provision",
        `        shared_secret: ${provisioningSecret}`,
        "    permissions:",
        `        "${homeserver.serverName}": user`,
        // Double puppeting: see `doublePuppet()`. The legacy generation spells
        // it with two maps under `bridge:` rather than a block of its own.
        "    double_puppet_server_map:",
        `        ${homeserver.serverName}: ${homeserver.baseUrl}`,
        "    double_puppet_allow_discovery: false",
        "    login_shared_secret_map:",
        `        ${homeserver.serverName}: as_token:${asToken}`,
        "logging:",
        "    min_level: warn",
        "    writers:",
        "    - type: stdout",
        "      format: pretty-colored",
        "",
      ].join("\n");
    // Written before `appservice:` only for readability; the binary upgrades
    // the file in place and key order carries no meaning.
    const network = bridge.network
      ? [
          "network:",
          ...Object.entries(bridge.network).map(
            ([key, value]) => `    ${key}: ${value}`,
          ),
        ]
      : [];
    return [
      "homeserver:",
      `    address: ${homeserver.baseUrl}`,
      `    domain: ${homeserver.serverName}`,
      "    software: standard",
      ...network,
      "appservice:",
      `    id: ${bridge.name}`,
      `    address: http://127.0.0.1:${bridge.port}`,
      "    hostname: 127.0.0.1",
      `    port: ${bridge.port}`,
      `    as_token: ${asToken}`,
      `    hs_token: ${hsToken}`,
      "    bot:",
      `        username: ${bridge.name}bot`,
      "database:",
      "    type: sqlite3-fk-wal",
      "    uri: file:bridge.db?_txlock=immediate",
      "bridge:",
      "    permissions:",
      `        "${homeserver.serverName}": user`,
      // See `repairCleanupOnLogout`: without this a logged-out account's
      // portals stay in the hub forever.
      "    cleanup_on_logout:",
      "        enabled: true",
      "        manual:",
      "            private: delete",
      "            relayed: delete",
      "            shared_no_users: delete",
      "            shared_has_users: delete",
      // Import a small recent window immediately. The persistent queue below
      // archives older ranges once and records its progress in the bridge DB.
      "backfill:",
      "    enabled: true",
      `    max_initial_messages: ${INITIAL_BACKFILL}`,
      `    max_catchup_messages: ${CATCHUP_BACKFILL}`,
      "    queue:",
      // Completed tasks stay complete across bridge restarts; only unfinished
      // ranges resume. This may produce sync notifications while the one-time
      // archive is still being built, but does not rebuild a finished archive.
      "        enabled: true",
      "        batch_size: 100",
      "        batch_delay: 20",
      "        max_batches: -1",
      ...doublePuppet(homeserver.serverName, homeserver.baseUrl, asToken),
      "provisioning:",
      `    shared_secret: ${provisioningSecret}`,
      "    allow_matrix_auth: true",
      "encryption:",
      "    allow: false",
      "    default: false",
      "logging:",
      "    min_level: warn",
      "    writers:",
      "    - type: stdout",
      "      format: pretty-colored",
      "",
    ].join("\n");
  }
}

/**
 * Replaces a config's `network:` block, or appends one when the bridge's
 * config has none yet. Everything else in the file — including whatever the
 * binary added when it upgraded the config in place — is left alone.
 */
/**
 * Conservative recent-history budgets. These match Mautrix's messaging-first
 * defaults: enough context for a new or reconnected portal without asking a
 * phone-backed network for thousands of messages after every desktop restart.
 */
const INITIAL_BACKFILL = 50;
const CATCHUP_BACKFILL = 500;

/**
 * Restores a config's `backfill:` block to Polymux's archive policy: bounded
 * recent backfill and the persistent backwards queue stay on, while old
 * aggressive immediate budgets are reduced. Queue progress lives in the
 * bridge database, so restarting resumes unfinished work rather than starting
 * completed tasks again.
 *
 * Walked line by line; see {@link withinBlock}.
 */
function repairBackfill(source: string): string {
  let inQueue = false;
  return withinBlock(source, "backfill", (line) => {
    const directChild = line.match(/^[ \t]{1,4}([A-Za-z_][\w-]*):/);
    if (directChild) inQueue = directChild[1] === "queue";
    if (inQueue)
      return line.replace(/^([ \t]+enabled:[ \t]*)false\b/, "$1true");
    return line
      .replace(/^([ \t]{1,4}enabled:[ \t]*)false\b/, "$1true")
      .replace(
        /^([ \t]{1,4}max_initial_messages:[ \t]*)\d+\b/,
        `$1${INITIAL_BACKFILL}`,
      )
      .replace(
        /^([ \t]{1,4}max_catchup_messages:[ \t]*)\d+\b/,
        `$1${CATCHUP_BACKFILL}`,
      );
  });
}

/**
 * Keeps WhatsApp history sync incremental.
 *
 * `request_full_sync` is sent to the phone when the bridge logs in. Polymux
 * used to force it on with a ten-year, five-gigabyte budget. A desktop restart
 * could therefore make the phone announce another linked-device sync. Normal
 * incremental live sync handles new messages after pairing. The separate
 * persistent queue may finish archiving older ranges, but this login-time full
 * export request remains off so each restart does not request the archive anew.
 */
function repairHistorySync(source: string): string {
  return withinBlock(source, "network", (line) =>
    line
      .replace(/^([ \t]+request_full_sync:[ \t]*)true\b/, "$1false")
      .replace(/^([ \t]+days_limit:[ \t]*)\d+\b/, "$1null")
      .replace(/^([ \t]+size_mb_limit:[ \t]*)\d+\b/, "$1null")
      .replace(/^([ \t]+storage_quota_mb:[ \t]*)\d+\b/, "$1null"),
  );
}

/**
 * Rewrites the lines of one top-level block, leaving the rest of the file
 * exactly as it was — comments, ordering, indentation and all.
 *
 * Line by line rather than by regex: these blocks are nested three deep with a
 * comment above every key, and a pattern that spans that reliably is also one
 * that backtracks catastrophically on the shape it has to reject. An earlier
 * pair of them wedged the main process for minutes at startup.
 */
function withinBlock(
  source: string,
  block: string,
  rewrite: (line: string) => string,
): string {
  const lines = source.split("\n");
  const start = lines.findIndex((line) =>
    new RegExp(`^${block}:[ \t]*$`).test(line),
  );
  if (start < 0) return source;
  for (let index = start + 1; index < lines.length; index += 1) {
    // A blank line inside a block is legal; an unindented one ends it.
    if (lines[index].trim() !== "" && !/^[ \t]/.test(lines[index])) break;
    lines[index] = rewrite(lines[index]);
  }
  return lines.join("\n");
}

/**
 * Makes a logout the user asked for take its portals with it.
 *
 * The binaries default every cleanup action to `nothing`, so ending a session
 * leaves every room that session created joined and named as before. The chat
 * list still shows the old account's conversations, sending in one fails with
 * "you're not logged in", and signing in with a different account files its
 * portals *beside* the stale ones rather than replacing them — the second
 * account looks like it never linked.
 *
 * Only `manual:`. `bad_credentials:` is the network invalidating a session,
 * which is routinely transient, and deleting a year of history over a
 * reconnect is not something the user can undo.
 *
 * Edits the lines already there rather than writing the block: the binary
 * writes its own defaults over the whole config every time it reads one, so
 * this runs against a file that always has the keys in it.
 */
function repairCleanupOnLogout(source: string): string {
  const lines = source.split("\n");
  const start = lines.findIndex((line) =>
    /^[ \t]+cleanup_on_logout:[ \t]*$/.test(line),
  );
  if (start < 0) return source;
  const depth = indentWidth(lines[start]);
  let section: string | null = null;
  let changed = false;
  for (let index = start + 1; index < lines.length; index += 1) {
    const line = lines[index];
    if (line.trim() === "" || line.trimStart().startsWith("#")) continue;
    // An entry at or above the block's own indentation is the next block.
    if (indentWidth(line) <= depth) break;
    const entry = /^[ \t]*([A-Za-z0-9_]+):[ \t]*(.*?)[ \t]*$/.exec(line);
    if (!entry) continue;
    const [, key, value] = entry;
    // A key with nothing after it opens `manual:` or `bad_credentials:`, which
    // carry the same action names as each other — hence the tracking.
    if (value === "") {
      section = key;
      continue;
    }
    if (key === "enabled" && value === "false") {
      lines[index] = line.replace(/false\b/, "true");
      changed = true;
    } else if (section === "manual" && value === "nothing") {
      lines[index] = line.replace(/nothing\b/, "delete");
      changed = true;
    }
  }
  return changed ? lines.join("\n") : source;
}

function indentWidth(line: string): number {
  return /^[ \t]*/.exec(line)?.[0].length ?? 0;
}

/** A `double_puppet:` block, however much of it the binary has filled in. */
const DOUBLE_PUPPET_BLOCK = /^double_puppet:\n(?:[ \t][^\n]*\n|\n)*/m;

/** The appservice token a config was seeded with, so a repair can reuse it. */
const AS_TOKEN = /^[ \t]+as_token:[ \t]*(\S+)/m;

/** One scalar nested below `appservice:` in a machine-generated config. */
function nestedScalar(source: string, key: "as_token" | "hs_token"): string | null {
  const match = source.match(
    new RegExp(`^[ \\t]+${key}:\\s*(?:"([^"]*)"|'([^']*)'|(\\S+))\\s*$`, "m"),
  );
  return match?.[1] ?? match?.[2] ?? match?.[3] ?? null;
}

/** Makes the bridge config authenticate with the registration installed in the homeserver. */
function withRegistrationTokens(
  source: string,
  registration: Pick<ParsedRegistration, "asToken" | "hsToken">,
): string {
  const previousAsToken = nestedScalar(source, "as_token");
  const replace = (input: string, key: "as_token" | "hs_token", value: string) =>
    input.replace(
      new RegExp(`^([ \\t]+${key}:[ \\t]*)(?:"[^"]*"|'[^']*'|\\S+)([ \\t]*)$`, "m"),
      (_line, prefix: string, suffix: string) => `${prefix}${value}${suffix}`,
    );
  let reconciled = replace(source, "as_token", registration.asToken);
  reconciled = replace(reconciled, "hs_token", registration.hsToken);
  if (previousAsToken && previousAsToken !== registration.asToken)
    reconciled = reconciled
      .split(`as_token:${previousAsToken}`)
      .join(`as_token:${registration.asToken}`);
  return reconciled;
}

/**
 * What lets a bridge write a message as the user rather than as a ghost.
 *
 * Without it, everything the user sent from WhatsApp itself arrives from the
 * puppet of their own number, so the thread cannot tell their side from the
 * other person's — every message looks like it came from the contact. The
 * secret is the bridge's own appservice token: this homeserver is local,
 * single user and never federates, and it accepts an appservice speaking as
 * the human it was installed for (see `Homeserver#authenticate`).
 */
function doublePuppet(
  serverName: string,
  baseUrl: string,
  asToken: string,
): string[] {
  return [
    "double_puppet:",
    "    servers:",
    `        ${serverName}: ${baseUrl}`,
    "    secrets:",
    `        ${serverName}: as_token:${asToken}`,
    "    allow_discovery: false",
  ];
}

/**
 * Brings a config seeded by an earlier Polymux up to the current seed: safe
 * incremental history, the backfill queue, then double puppeting. Returns the source
 * unchanged when there is nothing to do, which is the steady state.
 */
export function repairConfig(
  source: string,
  options: {
    serverName: string;
    baseUrl: string;
    legacy?: boolean;
    platform?: string;
  },
): string {
  const { serverName, baseUrl, legacy, platform } = options;
  let repaired = repairHistorySync(repairBackfill(source));
  if (platform === "instagram") repaired = repairInstagramMediaFetch(repaired);
  // A legacy config keeps double puppeting as two maps nested under `bridge:`,
  // so there is no top-level block to swap wholesale. It is left to the seed:
  // the one bridge in that generation reseeds itself anyway when its layout is
  // wrong, and rewriting nested YAML by regex is how a config gets corrupted.
  if (legacy) return repaired;
  repaired = repairCleanupOnLogout(repaired);
  const asToken = AS_TOKEN.exec(repaired)?.[1];
  if (!asToken) return repaired;
  const block = `${doublePuppet(serverName, baseUrl, asToken).join("\n")}\n`;
  if (DOUBLE_PUPPET_BLOCK.test(repaired)) {
    // Only a secret for *this* server counts as configured. What the binary
    // writes back when it upgrades a config in place is its documentation —
    // `example.com: as_token:foobar`, and a servers map naming
    // anotherserver.example.org — which is a filled-in block that double
    // puppets nobody, and is what a check for "has any secret" reads as done.
    if (repaired.includes(`${serverName}: as_token:${asToken}`)) return repaired;
    // The trailing newline replaces the blank line the match swallowed, so the
    // sections after it stay separated the way the rest of the file is.
    return repaired.replace(DOUBLE_PUPPET_BLOCK, `${block}\n`);
  }
  return `${repaired.replace(/\n*$/, "\n")}${block}`;
}

/** The bridge writes these switches as true in older configs, which makes a
 * backfilled reel indistinguishable from an ordinary image in the client. */
function repairInstagramMediaFetch(source: string): string {
  const match = /^network:\n(?:[ \t]+.*\n?)*/m.exec(source);
  if (!match) return source;
  const network = match[0].replace(
    /^([ \t]+disable_xma_(?:backfill|always):[ \t]*)true([ \t]*(?:#.*)?)$/gm,
    "$1false$2",
  );
  return (
    source.slice(0, match.index) +
    network +
    source.slice(match.index + match[0].length)
  );
}

export function withNetwork(
  source: string,
  values: Record<string, string>,
): string {
  const block = [
    "network:",
    ...Object.entries(values).map(([key, value]) => `    ${key}: ${value}`),
  ].join("\n");
  const existing = /^network:\n(?:[ \t]+.*\n?)*/m;
  if (existing.test(source)) return source.replace(existing, `${block}\n`);
  return `${source.replace(/\n*$/, "\n")}${block}\n`;
}

/**
 * Terminates a bridge left over from a previous Polymux that did not shut down
 * cleanly, identified by the pid file its supervisor wrote. A stale file whose
 * pid now belongs to some other program is the caveat; the window is narrow
 * (pid reuse between a crash and the next launch) and the alternative — two
 * bridges racing on one port and one login session — is strictly worse.
 */
export async function reapStalePid(pidPath: string): Promise<void> {
  const raw = await readFile(pidPath, "utf8").catch((): string => "");
  const pid = Number(raw.trim());
  if (Number.isInteger(pid) && pid > 1) {
    try {
      process.kill(pid, "SIGTERM");
      // Give it a moment to release its port before the replacement binds.
      for (let attempt = 0; attempt < 20; attempt += 1) {
        await new Promise((resolve) => setTimeout(resolve, 100));
        try {
          process.kill(pid, 0);
        } catch {
          break;
        }
      }
    } catch {
      // Already gone.
    }
  }
  await rm(pidPath, { force: true }).catch((): undefined => undefined);
}

interface ParsedRegistration {
  id: string | null;
  url: string | null;
  asToken: string;
  hsToken: string;
  senderLocalpart: string | null;
  receiveEphemeral: boolean;
  userNamespaces: string[];
}

/**
 * Reads the handful of flat fields and the user-namespace regexes out of a
 * registration file. Registrations are machine-generated with a fixed shape,
 * so a targeted extraction beats carrying a YAML dependency for one file.
 */
export function parseRegistration(source: string): ParsedRegistration {
  const scalar = (key: string): string | null => {
    const match = source.match(
      new RegExp(`^${key}:\\s*(?:"([^"]*)"|'([^']*)'|(\\S+))\\s*$`, "m"),
    );
    return match?.[1] ?? match?.[2] ?? match?.[3] ?? null;
  };
  const asToken = scalar("as_token");
  const hsToken = scalar("hs_token");
  if (!asToken || !hsToken)
    throw new Error(
      "The bridge registration is missing its tokens; delete it and restart to regenerate.",
    );
  const userNamespaces: string[] = [];
  for (const match of source.matchAll(
    /regex:\s*(?:"([^"]*)"|'([^']*)'|(\S+))/g,
  )) {
    const pattern = match[1] ?? match[2] ?? match[3];
    // Only user namespaces matter here; alias/room regexes never match a user id.
    if (pattern && pattern.includes("@"))
      userNamespaces.push(pattern.replace(/^\^|\$$/g, ""));
  }
  return {
    id: scalar("id"),
    url: scalar("url"),
    asToken,
    hsToken,
    senderLocalpart: scalar("sender_localpart"),
    // Stable since Matrix v1.13. Keep the MSC2409 spelling for registrations
    // generated by older bridge binaries already installed on this Mac.
    receiveEphemeral:
      scalar("receive_ephemeral") === "true" ||
      /^de\.sorunome\.msc2409\.push_ephemeral:\s*true\s*$/m.test(source),
    userNamespaces,
  };
}
