/** Browser / extension entry. No Node builtins. */
export {
  ACCOUNT_SESSION_KEY,
  DESKTOP_OFFLINE,
  FetchVaultCloud,
  VaultSession,
  MISSING_CLOUD_VAULT,
  PolymuxAccountClient,
  authCodeFromUrl,
  base64ToBytes,
  bytesToBase64,
  isDesktopOffline,
  createPasskeyCredential,
  getPasskeyAssertion,
  listPasskeysForRequest,
  matchItems,
  parseVaultBlob,
  relyingPartyMatches,
  rpIdAllowedForOrigin,
  rpIdForOrigin,
  preferDesktopLoopback,
  pullAccountVault,
  resolveAccountConfig,
  shouldUseCloudSync,
  syncSessionWithCloud,
} from "./index.js";
